[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graphcore"
version = "0.1.0"
description = "A reusable framework for writing LLM-powered applications that iterate using various client side tools"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "GPL-3.0"}
authors = [
    {name = "Certora Ltd."}
]

dependencies = [
    "langchain-core==0.3.79",
    "langchain==0.3.27",
    "langchain-anthropic==0.3.21",
    "langgraph-sdk==0.2.6",
    "langgraph==0.6.7",
    "psycopg==3.2.12",
    "psycopg-binary==3.2.12",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["graphcore*"]
